# Generated by Django 3.1 on 2020-08-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('puuid', models.CharField(max_length=78, primary_key=True, serialize=False)),
                ('accountid', models.CharField(blank=True, max_length=56, null=True)),
                ('summonerid', models.CharField(blank=True, max_length=48, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('tier', models.TextField(blank=True, null=True)),
                ('summonername', models.TextField(blank=True, null=True)),
                ('leaguepoints', models.IntegerField(blank=True, null=True)),
                ('rank', models.TextField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('veteran', models.BooleanField(blank=True, null=True)),
                ('inactive', models.BooleanField(blank=True, null=True)),
                ('freshblood', models.BooleanField(blank=True, null=True)),
                ('hotstreak', models.BooleanField(blank=True, null=True)),
                ('profileiconid', models.IntegerField(blank=True, null=True)),
                ('revisiondate', models.CharField(blank=True, max_length=13, null=True)),
                ('summonerlevel', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
